### ISSUE TITLE
Memory limit and Timeout within Ajax request?

### ISSUE THREAD

**Issue by 360noscope** [christophetd/code-execution-api-demo#1]
Hi i'm new face with python docker sandbox i just wanna ask if i can specify timeout limit and also memory limit in ajax request to run code? I making something called judge that got plenty of python exercise and every exercise got different timeout and memory limit thanks 😄

**Comment by christophetd** [comment]
Yes, you can. You would need to add those parameters in the client-side code, and use them when calling `sandbox.run` ([here](https://github.com/christophetd/code-execution-api-demo/blob/master/api/handler.js#L26))

**Comment by 360noscope** [comment]
Thanks! looking for those line for a long time. 😆
